import tvm.relay as relay

def loadAndPrintLayers(file_name):
    # file_name is the path to output_tensors.params (generated by GraphModuleDebug)
    with open(file_name, 'rb') as fin:
        content = fin.read()
        result = relay.load_param_dict(bytearray(content))
        print (result)

if __name__ == '__main__':
    loadAndPrintLayers('./debug_z_decoder/_tvmdbg_device_CPU_0/output_tensors.params')
